### ISSUE TITLE
Neo4j graph generation

### ISSUE THREAD

**Issue by mhirna** [googleinterns/data-dependency-graph-analysis#1]
To be able to generate a graph we need to:

- [x] create a class that will handle cypher queries #2 
- [x] read parameters and statistics from a predefined config #3 
- [x] implement logic behind random graph generation using provided statistics #4
