### ISSUE TITLE
Parameter-based generation

### ISSUE THREAD

**Issue by mhirna** [googleinterns/data-dependency-graph-analysis#4]
Having config statistics we need to generate a random graph. To do so, we need to build the logic between different graph aspects, including:

- [x] how to assign entities to collections #7 
- [x] how to generate various attributes (text, number, enum) #12 
- [x] how to generate system <-> dataset relationship #7
