### ISSUE TITLE
Aggregate generation 

### ISSUE THREAD

**Issue by mhirna** [googleinterns/data-dependency-graph-analysis#6]
Create a module that will connect all parts of generation, including connections, attributes and generate neo4j graph.

**Comment by mhirna** [comment]
- [x] add proto generation #15 
- [x] add igraph generation #16 
- [x] add networkx generation #22 
- [x] get networkx from proto binary #25 
- [x] generate graph of any format from config #24
